# Generated by Django 6.0.1 on 2026-01-14 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('client_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('qr_code_data', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.CharField(help_text='Трек-код из Китая', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Например: Кроссовки', max_length=255)),
                ('weight', models.FloatField(default=0.0, help_text='Вес в кг')),
                ('status', models.CharField(choices=[('china_warehouse', 'На складе в Китае'), ('in_transit', 'В пути (Фура)'), ('arrived_dushanbe', 'Прибыл в Душанбе'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Выдан клиенту')], default='china_warehouse', max_length=50)),
                ('shelf_location', models.CharField(blank=True, help_text='Например: A-2', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics.clientprofile')),
            ],
        ),
    ]
