# Generated by Django 6.0.1 on 2026-01-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профили клиентов'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AddField(
            model_name='package',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Доп. услуги (с)'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='package',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='package_photos/', verbose_name='Фото посылки'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Цена за кг (с)'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ИТОГО к оплате (с)'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код клиента'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=100, verbose_name='Данные QR'),
        ),
        migrations.AlterField(
            model_name='package',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics.clientprofile', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание (Кроссовки)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ячейка на складе (А-2)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('china_warehouse', '🇨🇳 На складе в Китае'), ('in_transit', '🚛 В пути (Фура)'), ('arrived_dushanbe', '🇹🇯 Прибыл в Душанбе'), ('ready_for_pickup', '📦 Готов к выдаче'), ('delivered', '✅ Выдан клиенту')], default='china_warehouse', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='package',
            name='track_code',
            field=models.CharField(help_text='Трек-код с китайской наклейки', max_length=100, unique=True, verbose_name='Трек-код'),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес (кг)'),
        ),
    ]
