# Generated by Django 6.0.1 on 2026-01-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_clientprofile_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='extra_cost',
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Цена за кг ($)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ячейка'),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='К оплате ($)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='track_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Трек-код'),
        ),
    ]
