# Generated by Django 6.0.1 on 2026-01-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_package_extra_cost_alter_package_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, verbose_name='Сообщение (Что везем?)')),
                ('status', models.CharField(choices=[('new', '🔥 Новая заявка'), ('contacted', '📞 В обработке'), ('completed', '✅ Клиент зарегистрирован'), ('canceled', '❌ Отмена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
