# Generated by Django 6.0 on 2026-02-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('china_warehouse', '🇨🇳 На складе в Китае'), ('in_transit', '🚛 В пути (Фура)'), ('arrived_dushanbe', '🇹🇯 Прибыл в Душанбе'), ('ready_for_pickup', '📦 Готов к выдаче'), ('delivered', '✅ Выдан клиенту')], max_length=50, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Локация (Город/Склад)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='logistics.package', verbose_name='Посылка')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История перемещений',
                'ordering': ['-created_at'],
            },
        ),
    ]
