# Generated by Django 6.0 on 2026-02-25 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_packagehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('expected', '⏳ Ожидается'), ('china_warehouse', '🇨🇳 На складе в Китае'), ('in_transit', '🚛 В пути (Фура)'), ('arrived_dushanbe', '🇹🇯 Прибыл в Душанбе'), ('ready_for_pickup', '📦 Готов к выдаче'), ('delivered', '✅ Выдан клиенту')], default='china_warehouse', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='status',
            field=models.CharField(choices=[('expected', '⏳ Ожидается'), ('china_warehouse', '🇨🇳 На складе в Китае'), ('in_transit', '🚛 В пути (Фура)'), ('arrived_dushanbe', '🇹🇯 Прибыл в Душанбе'), ('ready_for_pickup', '📦 Готов к выдаче'), ('delivered', '✅ Выдан клиенту')], max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
