# Generated by Django 6.0 on 2026-02-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_clientprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('warehouse', 'Складчик')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
