# Generated by Django 6.0 on 2026-03-17 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_clientprofile_options_clientprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено'),
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('pending', 'Ожидает курьера'), ('accepted', 'Принята курьером'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='logistics.clientprofile', verbose_name='Клиент')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('packages', models.ManyToManyField(related_name='delivery_requests', to='logistics.package', verbose_name='Посылки')),
            ],
            options={
                'verbose_name': 'Заявка на доставку',
                'verbose_name_plural': 'Заявки на доставку',
                'ordering': ['-created_at'],
            },
        ),
    ]
