# Generated by Django 6.0 on 2026-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_packagehistory_changed_by_deliveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время принятия'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
    ]
