# Generated by Django 6.0 on 2026-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProhibitedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True, verbose_name='Ключевое слово')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Запрещенный товар',
                'verbose_name_plural': 'Запрещенные товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('expected', '⏳  Едет на склад в Китае'), ('china_warehouse', '🇨🇳 📦На складе в Китае'), ('in_transit', '🚛 В пути (Фура)'), ('arrived_dushanbe', '🇹🇯 Прибыл в Душанбе'), ('ready_for_pickup', '📦 Готов к выдаче'), ('delivered', '✅ Выдан клиенту'), ('rejected', '❌ Отклонено / Запрещено')], default='china_warehouse', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='status',
            field=models.CharField(choices=[('expected', '⏳  Едет на склад в Китае'), ('china_warehouse', '🇨🇳 📦На складе в Китае'), ('in_transit', '🚛 В пути (Фура)'), ('arrived_dushanbe', '🇹🇯 Прибыл в Душанбе'), ('ready_for_pickup', '📦 Готов к выдаче'), ('delivered', '✅ Выдан клиенту'), ('rejected', '❌ Отклонено / Запрещено')], max_length=50, verbose_name='Статус'),
        ),
    ]
