# Generated by Django 6.0 on 2026-03-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_prohibiteditem_alter_package_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, unique=True, verbose_name='Оригинальное название')),
                ('display_name', models.CharField(max_length=255, verbose_name='Отображаемое название')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено из списка')),
            ],
            options={
                'verbose_name': 'Пользовательская декларация',
                'verbose_name_plural': 'Пользовательские декларации',
            },
        ),
    ]
