# Generated by Django 6.0 on 2026-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_customdeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='tg_language',
            field=models.CharField(default='ru', max_length=10, verbose_name='Язык в ТГ'),
        ),
    ]
