# Generated by Django 6.0 on 2026-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_clientprofile_telegram_id_clientprofile_tg_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_bokhtar', models.CharField(default='+992 000 000 00', max_length=30, verbose_name='Телефон (Бохтар)')),
                ('phone_qubodiyon', models.CharField(default='+992 000 000 00', max_length=30, verbose_name='Телефон (Қубодиён)')),
                ('warehouse_address_ru', models.TextField(default='г. Душанбе, ул. Примерная 1', verbose_name='Адрес склада (RU)')),
                ('warehouse_address_china', models.TextField(default='浙江省义乌市后宅街道柳青路1577号里面C区1楼 2号杜尚别仓库2号门', verbose_name='Адрес склада Китай')),
                ('tariff_text_ru', models.TextField(default='📦 Тарифы Kayhon Cargo:\n• 1–20 кг: 27 с/кг\n• 21–30 кг: 25 с/кг\n• 31+ кг: 23 с/кг', verbose_name='Тарифы (RU)')),
                ('tariff_text_en', models.TextField(default='📦 Kayhon Cargo Rates:\n• 1–20 kg: 27 som/kg\n• 21–30 kg: 25 som/kg\n• 31+ kg: 23 som/kg', verbose_name='Тарифы (EN)')),
                ('tariff_text_tj', models.TextField(default='📦 Нархҳои Kayhon Cargo:\n• 1–20 кг: 27 с/кг\n• 21–30 кг: 25 с/кг\n• 31+ кг: 23 с/кг', verbose_name='Тарифы (TJ)')),
            ],
            options={
                'verbose_name': 'Настройки компании',
                'verbose_name_plural': 'Настройки компании',
            },
        ),
    ]
