# Generated by Django 6.0 on 2026-03-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Изменить настройки компании', 'verbose_name_plural': 'Изменить настройки компании'},
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('warehouse', 'Складчик'), ('courier', 'Доставщик')], default='client', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='tariff_text_en',
            field=models.TextField(default='📦 Kayhon Cargo Tariffs:\n• 1–20 kg: 27 TJS/kg\n• 21–30 kg: 25 TJS/kg\n• 31+ kg: 23 TJS/kg', verbose_name='Тарифы (EN)'),
        ),
    ]
