# Generated by Django 6.0 on 2026-03-26 03:51

import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=logistics.models.get_avatar_upload_path, verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=logistics.models.get_package_photo_upload_path, verbose_name='Фото посылки'),
        ),
    ]
