# Generated by Django 6.0 on 2026-03-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_alter_clientprofile_avatar_alter_package_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='price_china_dushanbe',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=10, verbose_name='Цена Китай-Душанбе ($/кг)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='price_dushanbe_home',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='Цена доставки до дома (с.)'),
        ),
    ]
