# Generated by Django 6.0 on 2026-03-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_companysettings_price_china_dushanbe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='kg_per_cube',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Плотность (кг за м³)'),
        ),
    ]
