# Generated by Django 6.0 on 2026-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_companysettings_kg_per_cube'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='price_per_cube',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за куб ($/м³)'),
        ),
    ]
